# Generated by Django 6.1.1 on 2026-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Your first name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
