# Generated by Django 6.1.1 on 2026-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited at'),
        ),
    ]
